export const BASE_API_ORIGIN = process.env.NEXT_PUBLIC_BASE_API_ORIGIN!;
export const BASE_API_PATH = process.env.NEXT_PUBLIC_BASE_API_PATH!;
export const NOTION_BASE_DATABASE = process.env.NEXT_PUBLIC_NOTION_BASE_DATABASE!;
export const NOTION_BASE_BLOCK = process.env.NEXT_PUBLIC_NOTION_BASE_BLOCK!;
